/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CostBreakdown {
  'costPerUnit' : number,
  'ingredient' : string,
  'unit' : string,
  'totalCost' : number,
  'quantity' : number,
}
export interface DashboardStats {
  'totalIngredients' : bigint,
  'averageFoodCostPercentage' : number,
  'mostProducedItem' : string,
  'totalRecipes' : bigint,
}
export interface Ingredient {
  'quantityPerPortion' : number,
  'name' : string,
  'unit' : string,
}
export interface RawMaterial {
  'id' : bigint,
  'unitType' : string,
  'rawMaterialName' : string,
  'pricePerUnit' : number,
}
export interface RecipeCostAnalysis {
  'breakdown' : Array<CostBreakdown>,
  'costPerPortion' : number,
  'totalBatchCost' : number,
}
export interface _SERVICE {
  'addRawMaterial' : ActorMethod<[string, string, number], undefined>,
  'addRecipe' : ActorMethod<
    [string, string, number, Array<Ingredient>],
    undefined
  >,
  'calculateCost' : ActorMethod<[string, number], RecipeCostAnalysis>,
  'calculateProduction' : ActorMethod<
    [string, number],
    { 'totalPortionWeight' : number, 'ingredients' : Array<Ingredient> }
  >,
  'deleteRawMaterial' : ActorMethod<[bigint], undefined>,
  'editRawMaterial' : ActorMethod<[bigint, string, string, number], undefined>,
  'getAllCategories' : ActorMethod<[], Array<string>>,
  'getAllRawMaterials' : ActorMethod<[], Array<RawMaterial>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getRawMaterial' : ActorMethod<[bigint], [] | [RawMaterial]>,
  'getRecipesByCategory' : ActorMethod<[string], Array<string>>,
  'getStoreIssueSlip' : ActorMethod<
    [string, number],
    {
      'productionQuantity' : number,
      'recipeName' : string,
      'date' : string,
      'ingredients' : Array<Ingredient>,
    }
  >,
  'setIngredientCost' : ActorMethod<[string, number, string], undefined>,
  'setupAdmin' : ActorMethod<[], undefined>,
  'updateIngredientCost' : ActorMethod<[string, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];