/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Ingredient = IDL.Record({
  'quantityPerPortion' : IDL.Float64,
  'rawMaterialId' : IDL.Nat,
  'unit' : IDL.Text,
});
export const CostBreakdown = IDL.Record({
  'costPerUnit' : IDL.Float64,
  'totalCost' : IDL.Float64,
});
export const RecipeCostAnalysis = IDL.Record({
  'breakdown' : IDL.Vec(CostBreakdown),
  'costPerPortion' : IDL.Float64,
  'totalBatchCost' : IDL.Float64,
});
export const RawMaterial = IDL.Record({
  'id' : IDL.Nat,
  'unitType' : IDL.Text,
  'rawMaterialName' : IDL.Text,
  'pricePerUnit' : IDL.Float64,
});
export const DashboardStats = IDL.Record({
  'totalIngredients' : IDL.Nat,
  'averageFoodCostPercentage' : IDL.Float64,
  'mostProducedItem' : IDL.Text,
  'totalRecipes' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addRawMaterial' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
  'addRecipe' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Vec(Ingredient)],
      [],
      [],
    ),
  'calculateCost' : IDL.Func(
      [IDL.Text, IDL.Float64],
      [RecipeCostAnalysis],
      ['query'],
    ),
  'calculateProduction' : IDL.Func(
      [IDL.Text, IDL.Float64],
      [
        IDL.Record({
          'totalPortionWeight' : IDL.Float64,
          'ingredients' : IDL.Vec(Ingredient),
        }),
      ],
      ['query'],
    ),
  'checkHealth' : IDL.Func([], [IDL.Bool], ['query']),
  'deleteRawMaterial' : IDL.Func([IDL.Nat], [], []),
  'editRawMaterial' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64],
      [],
      [],
    ),
  'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllRawMaterials' : IDL.Func([], [IDL.Vec(RawMaterial)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getRawMaterial' : IDL.Func([IDL.Nat], [IDL.Opt(RawMaterial)], ['query']),
  'getRecipesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getStoreIssueSlip' : IDL.Func(
      [IDL.Text, IDL.Float64],
      [
        IDL.Record({
          'productionQuantity' : IDL.Float64,
          'recipeName' : IDL.Text,
          'date' : IDL.Text,
          'ingredients' : IDL.Vec(Ingredient),
        }),
      ],
      ['query'],
    ),
  'setupAdmin' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Ingredient = IDL.Record({
    'quantityPerPortion' : IDL.Float64,
    'rawMaterialId' : IDL.Nat,
    'unit' : IDL.Text,
  });
  const CostBreakdown = IDL.Record({
    'costPerUnit' : IDL.Float64,
    'totalCost' : IDL.Float64,
  });
  const RecipeCostAnalysis = IDL.Record({
    'breakdown' : IDL.Vec(CostBreakdown),
    'costPerPortion' : IDL.Float64,
    'totalBatchCost' : IDL.Float64,
  });
  const RawMaterial = IDL.Record({
    'id' : IDL.Nat,
    'unitType' : IDL.Text,
    'rawMaterialName' : IDL.Text,
    'pricePerUnit' : IDL.Float64,
  });
  const DashboardStats = IDL.Record({
    'totalIngredients' : IDL.Nat,
    'averageFoodCostPercentage' : IDL.Float64,
    'mostProducedItem' : IDL.Text,
    'totalRecipes' : IDL.Nat,
  });
  
  return IDL.Service({
    'addRawMaterial' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
    'addRecipe' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Vec(Ingredient)],
        [],
        [],
      ),
    'calculateCost' : IDL.Func(
        [IDL.Text, IDL.Float64],
        [RecipeCostAnalysis],
        ['query'],
      ),
    'calculateProduction' : IDL.Func(
        [IDL.Text, IDL.Float64],
        [
          IDL.Record({
            'totalPortionWeight' : IDL.Float64,
            'ingredients' : IDL.Vec(Ingredient),
          }),
        ],
        ['query'],
      ),
    'checkHealth' : IDL.Func([], [IDL.Bool], ['query']),
    'deleteRawMaterial' : IDL.Func([IDL.Nat], [], []),
    'editRawMaterial' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64],
        [],
        [],
      ),
    'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllRawMaterials' : IDL.Func([], [IDL.Vec(RawMaterial)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getRawMaterial' : IDL.Func([IDL.Nat], [IDL.Opt(RawMaterial)], ['query']),
    'getRecipesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getStoreIssueSlip' : IDL.Func(
        [IDL.Text, IDL.Float64],
        [
          IDL.Record({
            'productionQuantity' : IDL.Float64,
            'recipeName' : IDL.Text,
            'date' : IDL.Text,
            'ingredients' : IDL.Vec(Ingredient),
          }),
        ],
        ['query'],
      ),
    'setupAdmin' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };