/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RecipeCostAnalysis {
    breakdown: Array<CostBreakdown>;
    costPerPortion: number;
    totalBatchCost: number;
}
export interface RawMaterial {
    id: bigint;
    unitType: string;
    rawMaterialName: string;
    pricePerUnit: number;
}
export interface Ingredient {
    quantityPerPortion: number;
    name: string;
    unit: string;
}
export interface DashboardStats {
    totalIngredients: bigint;
    averageFoodCostPercentage: number;
    mostProducedItem: string;
    totalRecipes: bigint;
}
export interface CostBreakdown {
    costPerUnit: number;
    ingredient: string;
    unit: string;
    totalCost: number;
    quantity: number;
}
export interface backendInterface {
    addRawMaterial(rawMaterialName: string, unitType: string, pricePerUnit: number): Promise<void>;
    addRecipe(name: string, category: string, portionWeight: number, ingredients: Array<Ingredient>): Promise<void>;
    calculateCost(recipeName: string, quantity: number): Promise<RecipeCostAnalysis>;
    calculateProduction(recipeName: string, quantity: number): Promise<{
        totalPortionWeight: number;
        ingredients: Array<Ingredient>;
    }>;
    deleteRawMaterial(id: bigint): Promise<void>;
    editRawMaterial(id: bigint, rawMaterialName: string, unitType: string, pricePerUnit: number): Promise<void>;
    getAllCategories(): Promise<Array<string>>;
    getAllRawMaterials(): Promise<Array<RawMaterial>>;
    getDashboardStats(): Promise<DashboardStats>;
    getRawMaterial(id: bigint): Promise<RawMaterial | null>;
    getRecipesByCategory(category: string): Promise<Array<string>>;
    getStoreIssueSlip(recipeName: string, quantity: number): Promise<{
        productionQuantity: number;
        recipeName: string;
        date: string;
        ingredients: Array<Ingredient>;
    }>;
    setIngredientCost(ingredientName: string, costPerUnit: number, unit: string): Promise<void>;
    setupAdmin(): Promise<void>;
    updateIngredientCost(ingredientName: string, newCostPerUnit: number): Promise<void>;
}
import type { RawMaterial as _RawMaterial } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addRawMaterial(arg0: string, arg1: string, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRawMaterial(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRawMaterial(arg0, arg1, arg2);
            return result;
        }
    }
    async addRecipe(arg0: string, arg1: string, arg2: number, arg3: Array<Ingredient>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRecipe(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRecipe(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async calculateCost(arg0: string, arg1: number): Promise<RecipeCostAnalysis> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateCost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateCost(arg0, arg1);
            return result;
        }
    }
    async calculateProduction(arg0: string, arg1: number): Promise<{
        totalPortionWeight: number;
        ingredients: Array<Ingredient>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateProduction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateProduction(arg0, arg1);
            return result;
        }
    }
    async deleteRawMaterial(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRawMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRawMaterial(arg0);
            return result;
        }
    }
    async editRawMaterial(arg0: bigint, arg1: string, arg2: string, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editRawMaterial(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editRawMaterial(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getAllCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategories();
            return result;
        }
    }
    async getAllRawMaterials(): Promise<Array<RawMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRawMaterials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRawMaterials();
            return result;
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getRawMaterial(arg0: bigint): Promise<RawMaterial | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRawMaterial(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRawMaterial(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecipesByCategory(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecipesByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecipesByCategory(arg0);
            return result;
        }
    }
    async getStoreIssueSlip(arg0: string, arg1: number): Promise<{
        productionQuantity: number;
        recipeName: string;
        date: string;
        ingredients: Array<Ingredient>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStoreIssueSlip(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStoreIssueSlip(arg0, arg1);
            return result;
        }
    }
    async setIngredientCost(arg0: string, arg1: number, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setIngredientCost(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setIngredientCost(arg0, arg1, arg2);
            return result;
        }
    }
    async setupAdmin(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setupAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setupAdmin();
            return result;
        }
    }
    async updateIngredientCost(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIngredientCost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIngredientCost(arg0, arg1);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RawMaterial]): RawMaterial | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
